language: ruby
rvm:
- 1.9.3
services: redis
after_success:
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && curl -v -X DELETE -u $GITHUB_USER:$GITHUB_PASSWORD
  "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs/tags/CURRENT"'
- ! '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && curl -v -X POST -d ''{"ref":"refs/tags/CURRENT","sha":"''$TRAVIS_COMMIT''"}''  --header
  "Content-Type:application/json" -u $GITHUB_USER:$GITHUB_PASSWORD "https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs"'
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - ! '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always
env:
  global:
  - RESQUE_REDIS_HOST='localhost'
  - RESQUE_REDIS_PORT='6379'
  - CAPSULECRM_ACCOUNT_NAME='accountname'
  - CAPSULECRM_API_TOKEN='madeupkey'
  - secure: VxfTKf3VbPQCs8jB3Yif82WWeP2bN9JUwrn0npYxGZcrCn+AP/3MFYl/ZkPAAhiAk8xkNplMVvEYJUMypm58v0ok8ZNjoeYH2ACjQl4M9C5JEefrzXiqix+UZKXxxA/D9VaA1+THyRUoB877TdAE0Rqh44tOpGhzvE4bPPZJ7PE=
  - secure: bsyRv7XBZrvvvGRdVLcVjTn6FtSGfy/dsT4Llx7nd75kEIADGNLHVPAMvCJMrPC1dAwgBCoZTmXpyQZkQykezQxEoRKSJgdg8RFGMpBh4YL+ajZtZMJjAq+jlEbXWijyO7vjytZVkhzVc1yZ8Nex+6tpPwybcLCDAWE70mMhCDE=
