dashboard_time:
  every:
    - 1m
  class: DashboardTime
  args:
  description: "Updates the time on the dashboard every 1 minute"

github_issues:
  every:
    - 5m
  class: Github::IssueMonitor
  args:
  description: "Pulls issue count from Github"

github_organisation:
  every:
    - 1h
  class: Github::OrganisationMonitor
  args:
  description: "Pulls repository count from Github"

github_watchers:
  every:
    - 2h
  class: Github::WatchersForksMonitor
  args:
  description: "Pulls watcher/fork count from Github"

github_prs:
  every:
    - 10m
  class: Github::PullRequestMonitor
  args:
  description: "Pulls pull request counts from Github"

github_outgoing_prs:
  every:
    - 1h
  class: Github::OutgoingPullRequestMonitor
  args:
  description: "Pulls outgoing pull request count from Github"

trello:
  every:
    - 5m
  class: TrelloMonitor
  args:
  description: "Pulls information from Trello"

hubot:
  every:
    - 1m
  class: HubotMonitor
  args:
  description: "Count number of users in IRC"

eventbrite:
  every:
    - 1h
  class: EventMonitor
  args:
  description: "Interrogate all events in Eventbrite"

capsulesync:
  every:
    - 1h
  class: CapsuleSyncMonitor
  args:
  description: "Sync data back to member directory from CapsuleCRM"

import_resources:
  every:
    - 1h
  class: ImportResources
  args:
  description: "Imports and updates resources from Google Calendar"
  queue: office_calendar

membership_count:
  every:
    - 1d
  class: MembershipCount
  args:
  description: "Count members"

opportunity_monitor:
  every:
    - 1d
  class: OpportunityAgeMonitor
  args:
  description: "Calculate metrics for age of opportunities"

opportunity_reminders:
  cron: 0 0 * * 0
  class: SendOpportunityReminders
  args:
  description: "Send emails to remind about old opportunities"

membership_renewals:
  every:
    - 1d
  class: MembershipRenewals
  args:
  description: "Count members renewing"

pipeline_metrics:
  every:
    - 1d
  class: PipelineMetrics
  args:
  description: "Calculate pipeline stats"

membership_coverage:
  every:
    - 1d
  class: MembershipCoverage
  args:
  description: "Calculate membership coverage metrics"

google_drive_mover:
  every: 5m
  class: GoogleDrive::Mover
  args:
  description: "Moves Xero export into aggregate spreadsheet"

financial_metrics:
  every:
    - 1h
  class: FinancialMetrics
  args:
  description: "Gather financial metrics for dashboard"

network_metrics:
  every:
    - 1h
  class: NetworkMetrics
  args:
  description: "Gather network metrics for dashboard"

press_metrics:
  every:
    - 1h
  class: PressMetrics
  args:
  description: "Gather press metrics for dashboard"

quarterly_progress:
  every:
    - 1d
  class: QuarterlyProgress
  args:
  description: "How do I quarter?"

trello_cards:
  every:
    - 1h
  class: TrelloTasks
  args:
  description: "Gather cards from Trello boards for dashboard"

certificate_count:
  every:
    - 1d
  class: CertificateCount
  args:
  description: "Certificated Datasets into the Metrics API"

diversity_metrics:
  every:
    - 1d
  class: DiversityMetrics
  args:
  description: "Load diversity data into the Metrics API"
