application_errors:
  every:
    - 5m
  class: ApplicationErrors
  args:
  description: "Update Airbrake error count"

dependency_metrics:
  every:
    - 1d
  class: DependencyMetrics
  args:
  description: "Update dependency counts from Gemnasium"

github_issues:
  every:
    - 5m
  class: Github::IssueMonitor
  args:
  description: "Pulls issue count from Github"

github_organisation:
  every:
    - 1h
  class: Github::OrganisationMonitor
  args:
  description: "Pulls repository count from Github"

github_watchers:
  every:
    - 2h
  class: Github::WatchersForksMonitor
  args:
  description: "Pulls watcher/fork count from Github"

github_prs:
  every:
    - 10m
  class: Github::PullRequestMonitor
  args:
  description: "Pulls pull request counts from Github"

eventbrite:
  every:
    - 1h
  class: EventMonitor
  args:
  description: "Interrogate all events in Eventbrite"

capsulesync:
  every:
    - 1h
  class: CapsuleSyncMonitor
  args:
  description: "Sync data back to member directory from CapsuleCRM"

membership_count:
  every:
    - 1d
  class: MembershipCount
  args:
  description: "Count members"

opportunity_monitor:
  every:
    - 1d
  class: OpportunityAgeMonitor
  args:
  description: "Calculate metrics for age of opportunities"

opportunity_reminders:
  cron: 0 0 * * 0
  class: SendOpportunityReminders
  args:
  description: "Send emails to remind about old opportunities"

membership_renewals:
  every:
    - 1d
  class: MembershipRenewals
  args:
  description: "Count members renewing"

pipeline_metrics:
  every:
    - 1d
  class: PipelineMetrics
  args:
  description: "Calculate pipeline stats"

membership_coverage:
  every:
    - 1d
  class: MembershipCoverage
  args:
  description: "Calculate membership coverage metrics"

financial_metrics:
  every:
    - 1h
  class: FinancialMetrics
  args:
  description: "Gather financial metrics for dashboard"

network_metrics:
  every:
    - 1h
  class: NetworkMetrics
  args:
  description: "Gather network metrics for dashboard"

press_metrics:
  every:
    - 1h
  class: PressMetrics
  args:
  description: "Gather press metrics for dashboard"

quarterly_progress:
  every:
    - 1d
  class: QuarterlyProgress
  args:
  description: "How do I quarter?"

#trello_cards:
#  every:
#    - 1h
#  class: TrelloTasks
#  args:
#  description: "Gather cards from Trello boards for dashboard"

certificate_count:
  every:
    - 1d
  class: CertificateCount
  args:
  description: "Certificated Datasets into the Metrics API"

diversity_metrics:
  every:
    - 1d
  class: DiversityMetrics
  args:
  description: "Load diversity data into the Metrics API"

chargify_finance_report:
  cron: 0 1 1 * *
  class: ChargifyReportGenerator
  args:
  description: "Report last months membership revenue to finance at the beginning of the month"

sync_mailing_list:
  cron: 0 3 * * *
  class: SyncMailingList
  args:
  description: "Sync mailing list subscribers from Capsule"

